@host=http://localhost:3000/apiv1


POST {{host}}/auth/signup
Content-Type: application/json

{
    "username": "julio",
    "email": "jcgoza97@gmail.com",
    "password": "123"
}


###

POST {{host}}/auth/signup
Content-Type: application/json

{
    "username": "jcgoza",
    "email": "jcg@gmail.com",
    "password": "123"
}