@host=http://localhost:3000/apiv1
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNjU4NTE1OTQzLCJleHAiOjE2NTg1MTc3NDN9.nOpkwkx-FmitfTLqUQvA67Ut0B42lqyXVceBB0R2peE

GET {{host}}/product
?page=1
&pageSize=10
&category=Boys
Content-Type: application/json
x-access-token: {{token}}

{
}

###


GET {{host}}/product/
?page=2
&pageSize=10
Content-Type: application/json
x-access-token: {{token}}

{
}


###

GET {{host}}/product/
?name=sho
Content-Type: application/json
x-access-token: {{token}}

{
}


###

GET {{host}}/product/
?pageSize=10
&page=2
Content-Type: application/json
x-access-token: {{token}}

{
}


### 


GET {{host}}/product
?page=2
Content-Type: application/json
x-access-token: {{token}}

{
}

###

GET {{host}}/product/noStock
Content-Type: application/json
x-access-token: {{token}}

{
}

### 


GET {{host}}/product/count/
?name=short
?tag=boy
Content-Type: application/json
x-access-token: {{token}}

{
}

###

POST {{host}}/product/
Content-Type: application/json
x-access-token: {{token}}

{
    "name": "prodcuto pepe",
    "stokc": "541",
    "description": "58"
}


###

POST {{host}}/product/
Content-Type: application/json
x-access-token: {{token}}

{
    "name": "prodcuto pepe",
    "price": "58",
    "stokc": "541",
    "description": "58",
    "category": "1",
    "images": [
        {"url": "/asdasd/"},
        {"url": "/asdasd/asdad"},
        {"url": "/asd/asdghhhf"}
    ]
}

###

POST {{host}}/product/
Content-Type: application/json
x-access-token: {{token}}

{
    "name": "prodcuto pepe",
    "price": "58",
    "stokc": "541",
    "description": "58",
    "category": "1",
    "tags": [
        1, 2, 3
    ]
}

###

GET {{host}}/product/2
Content-Type: application/json
x-access-token: {{token}}

{
}


###

PUT  {{host}}/product/
Content-Type: application/json
x-access-token: {{token}}

{
    "sku": 1,
    "name": "prodcuto pepe",
    "price": "58",
    "stokc": "541",
    "description": "58",
    "category": "1",
    "tags": [
        1, 2, 3
    ]
}


###

PATCH  {{host}}/product/stock
Content-Type: application/json
x-access-token: {{token}}

{
    "sku": 1,
    "decrease": 1
}


###

DELETE  {{host}}/product/1
Content-Type: application/json
x-access-token: {{token}}

{
}

###

GET {{host}}/valoracion/byProduct/1
Content-Type: application/json
x-access-token: {{token}}

{
}